# Merging Cinemetrics and Box Office Mojo Data

In [2]:
import pandas as pd
import numpy as np
import pickle
import dateutil.parser
import string
import datetime
import os.path

In [3]:
with open(os.path.dirname('merge_df') + '../dfs/asl_df.pkl', 'r') as picklefile: 
    asl_df = pickle.load(picklefile)
asl_df.head()

   Title  Year          Director   ASL
0  11:14  2003      Marcks, Greg  4.28
1     21  2008   Luketic, Robert  3.63
2    300  2007      Snyder, Zack  4.17
3   2012  2009  Emmerich, Roland  3.00
4      $  1972   Brooks, Richard  4.90

In [3]:
with open(os.path.dirname('merge_df') + '../dfs/mojo_df.pkl', 'r') as picklefile:
    mojo_df = pickle.load(picklefile)
mojo_df.head()

,URL,Title,Domestic Total Gross,Budget,Date,Runtime,Rating,Widest Release,Genre,Director
0,http://www.boxofficemojo.com/movies/?id=10.htm,10,"$74,865,517",N/A,"October 5, 1979",2 hrs. 1 min.,R,None,Romantic Comedy,None
1,http://www.boxofficemojo.com/movies/?id=10000b...,"10,000 B.C.","$94,784,201",$105 million,"March 7, 2008",1 hrs. 49 min.,PG-13,"3,454 theaters",Period Adventure,Roland Emmerich
2,http://www.boxofficemojo.com/movies/?id=10000k...,"10,000 Km","$12,423",N/A,"July 10, 2015",1 hrs. 39 min.,R,11 theaters,Comedy / Drama,None
3,http://www.boxofficemojo.com/movies/?id=1000ae...,After Earth,"$60,522,097",$130 million,"May 31, 2013",1 hrs. 40 min.,PG-13,"3,401 theaters",Sci-Fi,M. Night Shyamalan
4,http://www.boxofficemojo.com/movies/?id=1000ti...,"1,000 Times Good Night","$53,895",N/A,"October 24, 2014",1 hrs. 57 min.,Unrated,24 theaters,Foreign,None

In [10]:
# cleaning asl dataset

asl_df_cleaned = asl_df.copy()

def clean_asl_title(title):
    if title[-5:] == ', The':
        title = 'The ' + title[:-5]
    if title[-4:] == ', An':
        title = 'An ' + title[:-4]
    if title[-3:] == ', A':
        title = 'A ' + title[:-3]
    return title

def director_format(director):
    try:
        full_name = director.split(', ')
        return full_name[1] + ' ' + full_name[0]
    except:
        return director

def make_float(asl):
    try:
        asl = float(asl)
    except:
        asl = np.nan
    return asl

def make_int(asl):
    try:
        asl = int(asl)
    except:
        asl = np.nan
    return asl

asl_df_cleaned['Title'] = asl_df_cleaned['Title'].apply(clean_asl_title)
asl_df_cleaned['Director'] = asl_df_cleaned['Director'].apply(director_format)
asl_df_cleaned['ASL'] = asl_df_cleaned['ASL'].apply(make_float)
asl_df_cleaned['Year'] = asl_df_cleaned['Year'].apply(make_int)
asl_df_cleaned.head()

   Title    Year         Director   ASL
0  11:14  2003.0      Greg Marcks  4.28
1     21  2008.0   Robert Luketic  3.63
2    300  2007.0      Zack Snyder  4.17
3   2012  2009.0  Roland Emmerich  3.00
4      $  1972.0   Richard Brooks  4.90

In [15]:
# cleaning mojo dataset

def to_date(datestring):
    if datestring == None or datestring == 'N/A':
        return None
    try:
        date = dateutil.parser.parse(datestring)
    except:
        return datestring
    return date

def money_to_int(moneystring):
    try:
        return int(moneystring.replace('$', '').replace(',', ''))
    except:
        return np.nan

def runtime_to_minutes(runtimestring):
    try:
        runtime = runtimestring.split()
        minutes = int(runtime[0])*60 + int(runtime[2])
        return minutes
    except:
        return np.nan

def budget_to_int(budgetstring):
    if budgetstring == None or budgetstring == 'N/A':
        return np.nan
    budgetstring = budgetstring.replace(' ', '').replace('$', '').replace(',', '')
    if '.' in budgetstring:
        budgetstring = budgetstring.replace('.', '').replace('million', '00000').replace('thousand', '00')
    else:
        budgetstring = budgetstring.replace('.', '').replace('million', '000000').replace('thousand', '000')
    return int(budgetstring)

def wide_release_to_int(widestring):
    try:
        widestring = widestring.replace(' ', '').replace(',', '').replace('theaters', '')
        return int(widestring)
    except:
        return np.nan

In [16]:
mojo_df_cleaned = mojo_df.copy()

mojo_df_cleaned['Date'] = mojo_df_cleaned['Date'].apply(to_date)
mojo_df_cleaned['Domestic Total Gross'] = mojo_df_cleaned['Domestic Total Gross'].apply(money_to_int)
mojo_df_cleaned['Budget'] = mojo_df_cleaned['Budget'].apply(budget_to_int)
mojo_df_cleaned['Runtime'] = mojo_df_cleaned['Runtime'].apply(runtime_to_minutes)
mojo_df_cleaned['Widest Release'] = mojo_df_cleaned['Widest Release'].apply(wide_release_to_int)

In [17]:
mojo_df_cleaned.head()

,URL,Title,Domestic Total Gross,Budget,Date,Runtime,Rating,Widest Release,Genre,Director
0,http://www.boxofficemojo.com/movies/?id=10.htm,10,74865517.0,NaN,1979-10-05 00:00:00,121.0,R,NaN,Romantic Comedy,None
1,http://www.boxofficemojo.com/movies/?id=10000b...,"10,000 B.C.",94784201.0,105000000.0,2008-03-07 00:00:00,109.0,PG-13,3454.0,Period Adventure,Roland Emmerich
2,http://www.boxofficemojo.com/movies/?id=10000k...,"10,000 Km",12423.0,NaN,2015-07-10 00:00:00,99.0,R,11.0,Comedy / Drama,None
3,http://www.boxofficemojo.com/movies/?id=1000ae...,After Earth,60522097.0,130000000.0,2013-05-31 00:00:00,100.0,PG-13,3401.0,Sci-Fi,M. Night Shyamalan
4,http://www.boxofficemojo.com/movies/?id=1000ti...,"1,000 Times Good Night",53895.0,NaN,2014-10-24 00:00:00,117.0,Unrated,24.0,Foreign,None

# Adding Strip Title and Year to DFs

In [19]:
def strip_title(title):
    title = title.replace(' ', '').lower()
    for char in string.punctuation:
        if char in title:
            title = title.replace(char, '')
    return title

In [20]:
mojo_df_cleaned['Strip Title'] = mojo_df_cleaned['Title'].apply(strip_title)
asl_df_cleaned['Strip Title'] = asl_df_cleaned['Title'].apply(strip_title)
mojo_df_cleaned.head()

,URL,Title,Domestic Total Gross,Budget,Date,Runtime,Rating,Widest Release,Genre,Director,Strip Title
0,http://www.boxofficemojo.com/movies/?id=10.htm,10,74865517.0,NaN,1979-10-05 00:00:00,121.0,R,NaN,Romantic Comedy,None,10
1,http://www.boxofficemojo.com/movies/?id=10000b...,"10,000 B.C.",94784201.0,105000000.0,2008-03-07 00:00:00,109.0,PG-13,3454.0,Period Adventure,Roland Emmerich,10000bc
2,http://www.boxofficemojo.com/movies/?id=10000k...,"10,000 Km",12423.0,NaN,2015-07-10 00:00:00,99.0,R,11.0,Comedy / Drama,None,10000km
3,http://www.boxofficemojo.com/movies/?id=1000ae...,After Earth,60522097.0,130000000.0,2013-05-31 00:00:00,100.0,PG-13,3401.0,Sci-Fi,M. Night Shyamalan,afterearth
4,http://www.boxofficemojo.com/movies/?id=1000ti...,"1,000 Times Good Night",53895.0,NaN,2014-10-24 00:00:00,117.0,Unrated,24.0,Foreign,None,1000timesgoodnight

In [21]:
mojo_df_cleaned['Date'] = pd.to_datetime(mojo_df_cleaned['Date'], errors='coerce')
mojo_df_cleaned['Year'] = pd.DatetimeIndex(mojo_df_cleaned['Date']).year
mojo_df_cleaned.head()

,URL,Title,Domestic Total Gross,Budget,Date,Runtime,Rating,Widest Release,Genre,Director,Strip Title,Year
0,http://www.boxofficemojo.com/movies/?id=10.htm,10,74865517.0,NaN,1979-10-05,121.0,R,NaN,Romantic Comedy,None,10,1979.0
1,http://www.boxofficemojo.com/movies/?id=10000b...,"10,000 B.C.",94784201.0,105000000.0,2008-03-07,109.0,PG-13,3454.0,Period Adventure,Roland Emmerich,10000bc,2008.0
2,http://www.boxofficemojo.com/movies/?id=10000k...,"10,000 Km",12423.0,NaN,2015-07-10,99.0,R,11.0,Comedy / Drama,None,10000km,2015.0
3,http://www.boxofficemojo.com/movies/?id=1000ae...,After Earth,60522097.0,130000000.0,2013-05-31,100.0,PG-13,3401.0,Sci-Fi,M. Night Shyamalan,afterearth,2013.0
4,http://www.boxofficemojo.com/movies/?id=1000ti...,"1,000 Times Good Night",53895.0,NaN,2014-10-24,117.0,Unrated,24.0,Foreign,None,1000timesgoodnight,2014.0

In [22]:
merged_df = mojo_df_cleaned.copy()
merged_df = merged_df.merge(asl_df_cleaned, on=['Strip Title', 'Year'])

In [23]:
print len(merged_df)
merged_df[1000:1010]

3833

,URL,Title_x,Domestic Total Gross,Budget,Date,Runtime,Rating,Widest Release,Genre,Director_x,Strip Title,Year,Title_y,Director_y,ASL
1000,http://www.boxofficemojo.com/movies/?id=dragon...,Dragonfly,30323400.0,60000000.0,2002-02-22,105.0,PG-13,2507.0,Romantic Thriller,Tom Shadyac,dragonfly,2002.0,Dragonfly,Tom Shadyac,4.70
1001,http://www.boxofficemojo.com/movies/?id=dragon...,Dragonheart,51367375.0,NaN,1996-05-31,88.0,PG-13,2193.0,Fantasy,Rob Cohen,dragonheart,1996.0,DragonHeart,Rob Cohen,4.00
1002,http://www.boxofficemojo.com/movies/?id=dragon...,Dragonslayer,14110013.0,NaN,1981-06-26,109.0,PG,NaN,Fantasy,None,dragonslayer,1981.0,Dragonslayer,Matthew Robbins,5.65
1003,http://www.boxofficemojo.com/movies/?id=dragon...,Dragon: The Bruce Lee Story,35113743.0,NaN,1993-05-07,120.0,PG-13,1985.0,Action Drama,Rob Cohen,dragonthebruceleestory,1993.0,Dragon: The Bruce Lee Story,Rob Cohen,4.96
1004,http://www.boxofficemojo.com/movies/?id=drdoli...,Doctor Dolittle,144156605.0,NaN,1998-06-26,85.0,PG-13,2871.0,Family Comedy,Betty Thomas,doctordolittle,1998.0,Doctor Dolittle,Betty Thomas,3.50
1005,http://www.boxofficemojo.com/movies/?id=drdoli...,Dr. Dolittle 2,112952899.0,70000000.0,2001-06-22,87.0,PG,3053.0,Family Comedy,Steve Carr,drdolittle2,2001.0,Dr. Dolittle 2,Steve Carr,3.30
1006,http://www.boxofficemojo.com/movies/?id=dreamc...,Dreamcatcher,33715436.0,68000000.0,2003-03-21,134.0,R,2945.0,Sci-Fi Horror,Lawrence Kasdan,dreamcatcher,2003.0,Dreamcatcher,Lawrence Kasdan,3.77
1007,http://www.boxofficemojo.com/movies/?id=dreamc...,Dreamchild,1215923.0,NaN,1985-10-04,94.0,PG,3.0,Unknown,None,dreamchild,1985.0,Dreamchild,Gavin Millar,6.90
1008,http://www.boxofficemojo.com/movies/?id=dreamt...,The Dream Team,28890240.0,NaN,1989-04-07,113.0,PG-13,1459.0,Comedy,Howard Zieff,thedreamteam,1989.0,The Dream Team,Howard Zieff,5.87
1009,http://www.boxofficemojo.com/movies/?id=dresse...,Dressed to Kill,31899000.0,6500000.0,1980-06-23,105.0,R,NaN,Thriller,Brian De Palma,dressedtokill,1980.0,Dressed to Kill,Brian De Palma,6.20

In [24]:
del merged_df['Strip Title']
del merged_df['Title_y']
del merged_df['Director_x']
merged_df = merged_df.rename(columns={'Title_x':'Title', 'Domestic Total Gross': 'DTG', 'Director_y': 'Director'})

In [25]:
merged_df.head()

,URL,Title,DTG,Budget,Date,Runtime,Rating,Widest Release,Genre,Year,Director,ASL
0,http://www.boxofficemojo.com/movies/?id=10.htm,10,74865517.0,NaN,1979-10-05,121.0,R,NaN,Romantic Comedy,1979.0,Blake Edwards,11.89
1,http://www.boxofficemojo.com/movies/?id=10000b...,"10,000 B.C.",94784201.0,105000000.0,2008-03-07,109.0,PG-13,3454.0,Period Adventure,2008.0,Roland Emmerich,2.82
2,http://www.boxofficemojo.com/movies/?id=101dal...,101 Dalmatians,136189294.0,NaN,1996-11-27,103.0,G,2901.0,Family Comedy,1996.0,Stephen Herek,3.50
3,http://www.boxofficemojo.com/movies/?id=102dal...,102 Dalmatians,66957026.0,85000000.0,2000-11-22,104.0,G,2704.0,Family Comedy,2000.0,Kevin Lima,3.20
4,http://www.boxofficemojo.com/movies/?id=10than...,10th & Wolf,54702.0,8000000.0,2006-08-18,110.0,R,6.0,Crime Drama,2006.0,Bobby Morresco,3.86

In [26]:
merged_df.dtypes

URL                       object
Title                     object
DTG                      float64
Budget                   float64
Date              datetime64[ns]
Runtime                  float64
Rating                    object
Widest Release           float64
Genre                     object
Year                     float64
Director                  object
ASL                      float64
dtype: object

In [27]:
with open('merged_df.pkl', 'w') as picklefile:
    pickle.dump(merged_df, picklefile)